### PR TITLE
Adopting pytest

### PR DESCRIPTION
**Pull request by bsravanin**
1. Switching from unittest assertions to basic assert statements.
2. Removing boilerplate code related to test suites.
3. Adding a TestCommand to setup.py, to run tests using pytest by default.
4. Fixing the fabfile changes -- print in dodo.py needs to be imported from future.
5. Adding a pytest.ini that runs doctests as well.

### CODE REVIEW

**Comment by bsravanin** [comment]
The build failure in Python 2.6 is because of the rounding bug that was [fixed in Python 2.7] (https://docs.python.org/dev/whatsnew/2.7.html#python-3-1-features).

@wackou, how would you like me to handle this?

1. I could change the example to something that passes in Python 2.6 (the way other examples do). This, I think, is plainly wrong way of doing things.
2. I could modify change_string to use Decimal instead of floating point. I don't mind this, though the downside is that I will be changing the behavior of a function for backwards compatibility.

Also, what are your expectations for the pull request to be eligible for a merge? Do you expect all commits to pass, or just the final commit? If you expect all commits to pass, I can either squash all the commits into one large commit, or edit the chain of commits into a different set and send as a separate pull request.

**Comment by wackou** [comment]
Sorry I haven't had time to look at the pull request in details yet, will try to go over it during the weekend. As for python 2.6, I'm thinking about dropping support for it altogether, I feel at this point it is only holding us back, quality-wise, and doesn't bring us any benefits. Python 2.7 was released 5 years ago already!

Other than that, don't bother with squashing the commits or otherwise rewriting the history, as long as the final result works and looks nice that's all I care about :smile:

**Comment by wackou** [comment]
looks good!

A few questions:
 - how can I enable stdout/stderr output for the tests while running them with py.test? eg: running the tests in ``test_matchtree.py`` should show:
```
test_base_tree (test_matchtree.TestMatchTree) ... ok
test_match (test_matchtree.TestMatchTree) ... WARNING  [guessit.matcher:checkFields] -- ---- PROPER-Xvid ----
WARNING  [guessit.matcher:checkFields] -- ADDITIONAL: 'properCount': '1'
WARNING  [guessit.matcher:checkFields] -- ---- Xvid PROPER ----
WARNING  [guessit.matcher:checkFields] -- ADDITIONAL: 'properCount': '1'
```
 - how can I run only the doctests?
 - you got some tabs instead of spaces inside the ``setup.py`` file (here for instance: https://github.com/wackou/guessit/pull/199/files#diff-2eeaed663bd0d25b7e608891384b7298R53, and here: https://github.com/wackou/guessit/pull/199/files#diff-2eeaed663bd0d25b7e608891384b7298R98)

**Comment by wackou** [comment]
oh, and please ignore the issues with python 2.6, I have decided I will drop support for it in the next release of guessit

**Comment by bsravanin** [comment]
For any additional options, you can either:
1. Use that option with the pytest command inside an activated virtualenv.
2. Add the option to pytest.ini if you want it to be used by default.
3. Give it as part of the -a of setup.py (see tox.ini, e.g.)

To show stdout/stderr, use the "-s" option.

You can use -k to filter in/out any tests. To run only doctests, use -k"not test_", so that it will exclude any test with "test_" in its name (which is all of the non-doctests).

Thanks for pointing out. Fixed tabs in setup.py and re-reviewed them in the rest of the changed files.

**Comment by wackou** [comment]
awesome, thanks for your answers!
I will remove support for python 2.6 over the coming days, so that all unittests pass.
Thanks for all the work :smile:

**Comment by bsravanin** [comment]
Thank you, @wackou.

**Pull request merged**
